/**
 * Created by lifetea on 2016/10/9.
 */
var certList  = [
    {
        id:1,
        name:'李松阳',
        lab:'呼吸内科',
        hospital:'天朝医院',
        title:'主治医师',
        skilled:'呼吸道感染',
        description:'男,硕士,第四军医',
        certStatus:1,
        authorStatus:false,
        action:""
    },
    {
        id:2,
        name:'苏东坡',
        lab:'消化科',
        hospital:'宋朝医院',
        title:'主治医师',
        skilled:'消化道道感染',
        description:'男,硕士,第四军医。。。',
        certStatus:2,
        authorStatus:true,
        action:""
    },
    {
        id:3,
        name:'李白',
        lab:'胸外科',
        hospital:'唐朝医院',
        certStatus:-1,
        authorStatus:false,
        action:""
    },
    {
        id:4,
        name:'李清照',
        lab:'妇科',
        hospital:'宋朝医院',
        certStatus:1,
        authorStatus:false,
        action:""
    },
    {
        id:5,
        name:'李松阳',
        lab:'呼吸内科',
        hospital:'天朝医院',
        certStatus:1,
        authorStatus:false,
        action:""
    },
    {
        id:6,
        name:'苏东坡',
        lab:'消化科',
        hospital:'宋朝医院',
        certStatus:2,
        authorStatus:false,
        action:""
    },
    {
        id:7,
        name:'李白',
        lab:'胸外科',
        hospital:'唐朝医院',
        certStatus:-1,
        authorStatus:false,
        action:""
    },
    {
        id:8,
        name:'李清照',
        lab:'妇科',
        hospital:'宋朝医院',
        certStatus:1,
        authorStatus:false,
        action:""
    },
    {
        id:9,
        name:'苏东坡',
        lab:'消化科',
        hospital:'宋朝医院',
        certStatus:2,
        authorStatus:false,
        action:""
    },
    {
        id:10,
        name:'李白',
        lab:'胸外科',
        hospital:'唐朝医院',
        certStatus:-1,
        authorStatus:false,
        action:""
    },
    {
        id:11,
        name:'李清照',
        lab:'妇科',
        hospital:'宋朝医院',
        certStatus:1,
        authorStatus:false,
        action:""
    },
    {
        id:12,
        name:'李松阳',
        lab:'呼吸内科',
        hospital:'天朝医院',
        certStatus:1,
        authorStatus:false,
        action:""
    },
    {
        id:13,
        name:'苏东坡',
        lab:'消化科',
        hospital:'宋朝医院',
        certStatus:2,
        authorStatus:false,
        action:""
    },
    {
        id:14,
        name:'李白',
        lab:'胸外科',
        hospital:'唐朝医院',
        certStatus:-1,
        authorStatus:false,
        action:""
    },
    {
        id:15,
        name:'李清照',
        lab:'妇科',
        hospital:'宋朝医院',
        certStatus:1,
        authorStatus:false,
        action:""
    },
];
export default certList