/**
 * Created by lifetea on 2016/11/14.
 * email: 494886251@qq.com
 * github: https://github.com/lifetea
 */
export  default [
    {
        id:1,
        startTime:8,
        endTime:9,
        type:1,
        diagnoseNum:0,
        subscribed:0
    },
    {
        id:2,
        startTime:9,
        endTime:10,
        type:1,
        diagnoseNum:0,
        subscribed:0
    },
    {
        id:3,
        startTime:10,
        endTime:11,
        type:1,
        diagnoseNum:0,
        subscribed:0
    },
    {
        id:4,
        startTime:11,
        endTime:12,
        type:1,
        diagnoseNum:0,
        subscribed:0
    },
    {
        id:5,
        startTime:12,
        endTime:13,
        type:2,
        diagnoseNum:0,
        subscribed:0
    },
    {
        id:6,
        startTime:13,
        endTime:14,
        type:2,
        diagnoseNum:0,
        subscribed:0
    },
    {
        id:7,
        startTime:14,
        endTime:15,
        type:2,
        diagnoseNum:0,
        subscribed:0
    },
    {
        id:8,
        startTime:15,
        endTime:16,
        type:2,
        diagnoseNum:0,
        subscribed:0
    },
    {
        id:8,
        startTime:16,
        endTime:17,
        type:2,
        diagnoseNum:0,
        subscribed:0
    },
    {
        id:8,
        startTime:17,
        endTime:18,
        type:2,
        diagnoseNum:0,
        subscribed:0
    },
    {
        id:9,
        startTime:18,
        endTime:19,
        type:3,
        diagnoseNum:0,
        subscribed:0
    },
    {
        id:10,
        startTime:19,
        endTime:20,
        type:3,
        diagnoseNum:0,
        subscribed:0
    },
    {
        id:11,
        startTime:20,
        endTime:21,
        type:3,
        diagnoseNum:0,
        subscribed:0
    },
    {
        id:12,
        startTime:21,
        endTime:22,
        type:3,
        diagnoseNum:0,
        subscribed:0
    },
    {
        id:13,
        startTime:22,
        endTime:23,
        type:3,
        diagnoseNum:0,
        subscribed:0
    },
    {
        id:14,
        startTime:23,
        endTime:24,
        type:3,
        diagnoseNum:0,
        subscribed:0
    }
]